### ISSUE TITLE
cannot find spinners.json after package with PyInstaller

### ISSUE THREAD

**Issue by raintears** [ManrajGrover/halo#33]
it looks awesome but after I package into executable I can't run it because it can't find the json file. what should i do to fix this?

**Comment by ManrajGrover** [comment]
Hey @raintears,

Thank you for using the package. I would need more information on how to reproduce this bug. Please fill out the template shared [here](https://github.com/ManrajGrover/halo/blob/master/.github/ISSUE_TEMPLATE.md) and comment here.

**Comment by toejough** [comment]
FWIW, I just ran into this problem and solved it with some `--add-data` flags to the pyinstaller command:

```fish
pyinstaller --add-data "<venv-path>/site-packages/cli-spinners/spinners.json:cli-spinners" --add-data "empty.txt:spinners" --onefile foo.py
```

The `empty.txt` file is just an empty file to make pyinstaller create the `spinners` directory, as the path causing the problem is `spinners/../cli-spinners/spinners.json`, and whoever's responsible for representing/loading that path doesn't do the resolution to just `cli-spinners/spinners.json`.

**Comment by ManrajGrover** [comment]
@raintears This sounds resolved to me with @toejough's approach. Yes, you would need to package the submodules for halo to work. I'll think whether we should remove submodules and bring everything into one repository but for now this is resolved.
