### ISSUE TITLE
Bug: Escape sequences leaking on stdout, even using the sys.stderr stream

### ISSUE THREAD

**Issue by ccc032** [ManrajGrover/halo#36]
## Description
When using a spinner with `stream=sys.stderr`, the escape sequences to hide/show the terminal's cursor will still be outputed to stdout. They are visible if stdout is redirected to a file and opened in a text editor/`cat -v`, or directly piped to `cat -v`. This messes with the program's normal output in any case. 

### System settings

- Operating System: Void Linux x64
- Terminal in use: kitty, also tried on xterm
- Python version: 3.6.4
- Halo version: 0.0.8
- `pip freeze` output:
```
    asciinema==1.4.0
    asn1crypto==0.24.0
    attrs==17.4.0
    Automat==0.6.0
    backports.shutil-get-terminal-size==1.0.0
    cffi==1.11.2
    chardet==3.0.4
    colorama==0.3.9
    colored==1.3.5
    constantly==15.1.0
    cryptography==2.1.4
    cssselect==1.0.3
    cursor==1.1.0
    enum34==1.1.6
    flake8==3.5.0
    halo==0.0.8
    hererocks==0.17.0
    httplib2==0.10.3
    hyperlink==17.3.1
    idna==2.6
    incremental==17.5.0
    Jinja2==2.10
    log-symbols==0.0.12
    lxml==4.1.1
    MarkupSafe==1.0
    mccabe==0.6.1
    numpy==1.13.3
    openshot-qt==2.4.1
    pew==1.1.2
    pipenv==9.0.1
    psutil==5.4.2
    pyasn1==0.4.2
    pyasn1-modules==0.2.1
    Pybooru==4.1.0
    pycairo==1.15.4
    pycodestyle==2.3.1
    pycparser==2.18
    pyflakes==1.6.0
    Pygments==2.2.0
    PyGObject==3.27.1
    PyOpenGL==3.1.0
    PyOpenGL-accelerate==3.1.0
    pyOpenSSL==17.5.0
    pyPEG2==2.15.2
    python-mpv==0.3.8
    PyYAML==3.12
    pyzmq==16.0.3
    qutebrowser==1.0.4
    ranger==1.8.1
    requests==2.18.4
```

## Steps to recreate
Run this script, piping its output to `cat -v` (e.g. `python3 script | cat -v`):
```
from halo import Halo
import sys
spinner = Halo(stream=sys.stderr)
spinner.start()
spinner.stop()
print("Testing")
```

## People to notify
@ManrajGrover

**Comment by ManrajGrover** [comment]
Hi @ccc032, thanks for reporting this. I believe this happens because of the dependency [cursor](https://github.com/GijsTimmers/cursor) being used where on [line 37](https://github.com/GijsTimmers/cursor/blob/master/cursor/cursor.py#L37), it outputs escape sequences. One way of fixing this would be to remove dependency and move the code to this library and allow streams to be passed. Another way would be to send a PR and wait for the project owner to accept and publish the changes on pip. I would love to keep this code in a separate repository of it's own as it could benefit others in their projects.

**Comment by ManrajGrover** [comment]
Updating things here, I've created an issue for this https://github.com/GijsTimmers/cursor/issues/2

**Comment by ManrajGrover** [comment]
@ccc032 This should be fixed now. Could you please try HEAD and check whether you are still facing this issue or not? I'll make a release for this soon.

**Comment by ccc032** [comment]
@ManrajGrover Everything works fine now, thanks.
